### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#173] opened 2015-07-17 09:07 UTC
[redux](https://github.com/gaearon/redux) as a flux alternative

Watch [Dan Abramov's talk on Hot Reloading with Time Travel.](https://www.youtube.com/watch?v=xsSnOQynTHs)

Ref #579

**Comment by timdoes** [comment] 2015-07-21 00:29
+1

**Comment by tanertopal** [comment] 2015-08-03 12:02
:+1:

**Comment by Hyra** [comment] 2015-08-26 21:03
😸

**Comment by MyBoon** [comment] 2015-08-27 19:15
Redux is pretty simple to integrate to react-starter-kit ... I can PR this feature if @koistya want it.

**Comment by mirchiseth** [comment] 2015-09-11 07:14
+1

**Comment by nmrony** [comment] 2015-09-22 15:10
+1

**Comment by vkammerer** [comment] 2015-10-14 14:16
+1

**Comment by leonprou** [comment] 2015-12-15 17:08
+1

**Comment by sebastianpicklum** [comment] 2015-12-24 18:40
+1

**Comment by damirv** [comment] 2016-01-29 15:19
+1

**Comment by rustanacexd** [comment] 2016-02-01 13:44
+1 yes please

**Comment by andyhu** [comment] 2016-02-02 00:32
+1

**Comment by tconroy** [comment] 2016-02-02 02:49
:+1: !!!

**Comment by learntoswim** [comment] 2016-02-23 00:54
+1

**Comment by joshua-robinson** [comment] 2016-03-13 05:04
+1

**Comment by rusenask** [comment] 2016-03-24 16:51
could we get some kind of discussion here instead of "+1" ? I am also for redux as it looks like a better and cleaner approach although it would be interesting to hear other opinions.

**Comment by tconroy** [comment] 2016-03-24 17:09
@rusenask I mean... that pretty much sums it up. It's a cleaner flux architecture pattern, and rapidly becoming the community favorite implementation. We could fork this starter kit into two variants (a Flux and a Redux version) if the maintainer isn't interested in swapping out for Redux, but I think it would be in the best interest of the community to do so.

**Comment by langpavel** [comment] 2016-04-14 12:15
@koistya I'm interesting in implementing redux to this project. Will be PR possibly accepted?

**Comment by koistya** [comment] 2016-04-14 12:19
@langpavel yes, it can be merged into `feature/redux` branch for now. The problem is that many developer prefer Relay over Redux. I need to conduct a poll to check how many RSK users would like to see Redux on the master branch, how many Relay, and how many would like to keep it Flux-agnostic.

**Comment by langpavel** [comment] 2016-04-14 12:24
@koistya I'm interesting in Relay too. I thing that can be possible and beneficial to have both but this will need some more digging

**Closed** 2016-05-03 20:52 UTC

**Comment by koistya** [comment] 2016-09-27 08:26
A bare minimum Redux integration (example)
https://github.com/kriasoft/react-starter-kit/pull/883
