### ISSUE TITLE
Why loading page twice?

### ISSUE THREAD

**Issue by d0ntth1nc** [kriasoft/react-starter-kit#139] opened 2015-06-15 16:09 UTC
When we open some page for first time, the server renders and returns it. After all the client makes another request to download the same page again and it's being re-rendered on the client side. Any chance to skip that?

**Comment by koistya** [comment] 2015-06-15 16:15
@d0ntth1nc good catch! I'm going to fix that in one of the upcoming updates. But if you have a suggestion how to fix that, your PR is more than welcome.

**Comment by d0ntth1nc** [comment] 2015-06-15 18:37
Okay, i think i found solution! [Here](http://pastebin.com/aurmcxWh) is the code!
According to [ReactAPI](https://facebook.github.io/react/docs/top-level-api.html) : 
> If you call React.render() on a node that already has this server-rendered markup, React will preserve it and only attach event handlers, allowing you to have a very performant first-load experience.

**Comment by korczis** [comment] 2015-06-25 15:56
:+1:

**Comment by korczis** [comment] 2015-07-09 12:50
Any news?

**Comment by stphnclysmth** [comment] 2015-09-03 17:18
One way to solve this is to mark React as an external dependency in the Webpack `tools/config.js`.

```javascript
const appConfig = merge({}, config, {
  externals: [
    'react'
  ]
...
}
```

**Comment by chentaixu** [comment] 2015-09-03 17:32
Ah! I didn't know it was mentioned before and opened another identical issue. I think the crux of this issue is caused by lacking the relation between 'server-rendering' and 'browser-rendering'. For 'server-rendering', it is implemented in server.js. So, when this part is being executed, it should express in some sort of way that the server-rending is being done. For 'browser-rendering', the render function should try to learn about the previous fact. So I think a modification for those two parts would be most appropriate. I would try coming up the solution. It shouldn't be hard. ; p

**Comment by langpavel** [comment] 2016-07-10 21:18
You can use feature/redux or another data backed.. See how translations are handled in feature/react-intl

**Comment by langpavel** [comment] 2016-07-13 05:55
Good point. This is really unresolved yet!

But it really cannot be without transferring state to client and on master branch this cannot be achieved.

In `feature/redux` it can be, see how translations are passed in `feature/react-intl` branch.

**Closed by langpavel** 2016-07-13 05:55 UTC

**Comment by LorisTujiba** [comment] 2017-11-14 08:36
this effects the page source, the page source that returned by the server is outdated or the old ones.
After that the server returned the initial data(the false one), client then reload the correct data, but the page source doesn't changed. How to correct this ?

**Comment by code-flu** [comment] 2023-09-13 20:51
When wrapped with React.StrictMode (which is how [[CRA template] ](https://github.com/facebook/create-react-app/blob/master/packages/cra-template-typescript/template/src/index.tsx) are setup), on development, renders will be called twice. This is done to catch bugs that might occurs when some setState functions are not pure. You can read [this](https://github.com/facebook/react/issues/12856#issuecomment-390206425) for more detail.

**Solutoin** - Remove React.StrictMode from src/index.tsx

https://stackoverflow.com/questions/61193122/react-default-create-react-app-app-component-rendered-twice
