### ISSUE TITLE
never get 404 in router

### ISSUE THREAD

**Issue by Kepro** [kriasoft/react-starter-kit#385] opened 2016-01-07 10:05 UTC
i try to load

/omg

and then i get /api/content?path=/omg 404 not found
but in router i get that error: the page '/omg' is not found.'

but i get statusCode 200 all of time i don't do any change to router or something using latest version checkouted today

**Comment by cenob8** [comment] 2016-01-07 20:47
+1

**Comment by sebastianandreasson** [comment] 2016-01-08 14:10
Note sure if it's the right approach, but also saw this and changed up the "/src/routes.js" file like this for the wildcard ContentPage route.

```javascript
on("*", async(state, next) => {
    const response = await fetch(`/api/templates?path=${state.path}`);
    const content = await response.json();
    if (!content.error) {
        return content && <ContentPage {...content}/>;
    }
    next();
});
```

**Comment by koistya** [comment] 2016-01-08 14:11
It seems like a regression bug after replacing `superagent` with WHATWG `fetch` module..

**Comment by Kepro** [comment] 2016-01-08 14:12
yes but this is not a solution...@koistya why you change from superagent? new library is better or?

**Comment by koistya** [comment] 2016-01-08 14:13
@Kepro it seems to be more promising, take a look at this blog post: https://jakearchibald.com/2015/thats-so-fetch/

**Comment by Kepro** [comment] 2016-01-08 14:15
nice :+1:

**Comment by sidhuko** [comment] 2016-02-21 10:48
Had same issue installing from Yeoman but was fixed on master branch. 
``` 
on('*', async (state) => {
    const response = await fetch(`/api/content?path=${state.path}`);
    const content = await response.json();
    return response.ok && content && <ContentPage {...content} />;
});
```

**Comment by koistya** [comment] 2016-04-08 20:38
This issue seems to be fixed on the `master` branch. Feel free to reopen.

**Closed by koistya** 2016-04-08 20:38 UTC
