### ISSUE TITLE
Server terminated unexpectedly with code: 0 signal: null

### ISSUE THREAD

**Issue by TristanDongMaster** [kriasoft/react-starter-kit#1532] opened 2018-02-06 09:22 UTC
**I want to  general the static html for every rounter, but failed for "npm run render".
 the cmd throw the follow ERROR:**
npm run render
->
throw new Error("Server terminated unexpectedly with code: ".concat(code, " signal: ").concat(signal));
^
Error: Server terminated unexpectedly with code: 0 signal: null
at ChildProcess. (/Users/tristan/workspace/github/react-starter-kit/tools/runServer.js:56:17)
at Object.onceWrapper (events.js:255:19)
at ChildProcess.emit (events.js:160:13)
at Process.ChildProcess._handle.onexit (internal/child_process.js

======================================
**other info:**
node -v
-> v9.4.0
yarn run build --release --static (it run success)
-> 
Asset Size Chunks Chunk Names
chunks/privacy.js 29.9 kB 0 [emitted] privacy
chunks/about.js 29.9 kB 1 [emitted] about
chunks/register.js 21.7 kB 2 [emitted] register
chunks/not-found.js 21.9 kB 3 [emitted] not-found
chunks/login.js 55.3 kB 4 [emitted] login
chunks/contact.js 21.6 kB 5 [emitted] contact

--------------------------------------------------------
i try to re-git-clone the react-starter-kit, it is the latest and fresh react-starter-kit/master, it is my ENV
node -v
-> v9.4.0

I need help, hurry online!!!!!!!!!!!!!!**

**Comment by TristanDongMaster** [comment] 2018-02-06 09:23
anybody can help me?

**Comment by TristanDongMaster** [comment] 2018-02-06 09:25
try remove node_modules and install fresh. but it still not work

**Comment by Larinel** [comment] 2018-02-06 10:08
Please, stop creating identical issues. Try other version of node(ex 8)

**Comment by langpavel** [comment] 2018-02-07 02:22
This is duplicate of #1530. Please do not spam us @TristanDongMaster.
Nobody can help you if you don't provide reproducible example.
I tested on the latest versions of node 6 and 7 and on all branches and `yarn build --release --static` works.
Only exception was if I run `render` task separately when not preceded by `build`. Note that you must maintain list of url what you want to prerender in [`tools/render.js`](https://github.com/kriasoft/react-starter-kit/blob/master/tools/render.js#L24)

**Comment by langpavel** [comment] 2018-02-07 02:22
Move on #1530

**Closed by langpavel** 2018-02-07 02:22 UTC
